### PR TITLE
[WIP] Add combineResults function.

### PR DESCRIPTION
**Pull request by j-andrews7**
Still need to write a test or two. Addresses #54.

### CODE REVIEW

**Comment by LTLA** [comment]
I thought we talked about taking the label corresponding to the max score across labels?

Having thought about it a bit more, I'm kind of worried by the fact that, currently, the correlations will be computed using different marker sets across references, which makes them not-very-comparable. We'll probably have to define a common marker set to use for all references prior to doing this combining thing; it should still be possible to evade any need for label harmonization, but we would need to wrap the entire process into another pair of `train`/`classify` functions.

**Comment by j-andrews7** [comment]
Ah, that's what I originally had, but after reading your comments on it, I thought I had misunderstood. 

I also considered having both this function and that one (was going to call the max score one `prioritizeResults` or `maxScore`). 

If that's the approach we want, I'm more inclined to just make providing multiple reference sets to `trainSingleR` possible, though that would be messing with current functionality, which I know is a no-go.

**Comment by LTLA** [comment]
Well, we can do it in BioC-devel, just not in release.

Prep the combining function first and we'll see how well it works first (if our test users follow the rules about using the same feature set) before expanding `trainSingleR` to enforce those rules.

**Comment by LTLA** [comment]
Is this the same as #59, or what?

**Comment by j-andrews7** [comment]
No, this was collating the labels from each result rather than picking a singular label based on the highest score across results. I can close it if you feel it's a moot point given #59 and #60.

**Comment by LTLA** [comment]
No probs, I'll close it.

**Pull request closed without merging**
