### PR TITLE
Updated plotCellVsReference inputs and fixed its testthat code

### PR DESCRIPTION
**Pull request by dtm2451**
visualizations.R, plotCellVsReference:
updated the assay.type inputs in plotCellVsReference to match the rest of the naming scheme:
 - assay.type.sc -> test.assay.type
 - assay.type.train -> ref.assay.type

test-visualizations.R:
Added back expression matrix grabbing in code's setup to facilitate the testing that plotCellVsReference can handle these as input.
Corrected proper assay.data inputs to look for non-existent data slots now that logcounts slot was added in the the setup.R file.

### CODE REVIEW

**Comment by LTLA** [comment]
> updated the assay.type inputs in plotCellVsReference to match the rest of the naming scheme:

Note that `SingleR()` uses `assay.type.test`. I'm fine with either version, but if you use your version, then make sure to rename the `SingleR()` argument as well.

> test-visualizations.R:

What's with the reversion to the wonky formatting?

Probably also good to explicitly name all the arguments in each call, if you're naming `test` and `ref`.

**Comment by dtm2451** [comment]
Is this re-updated formatting better?  Let me know if you would prefer I remove variable names and just go back to having everything on one line.  I had started adding them so it would be easier to tell what each line does when errors do get caught.

I've also changed the assay.type variables to assay.type.test/ref to match their names in SingleR.

Still to do is either:
- Add all other variable names in to the plotCellVsReference testthat code,
- OR remove all variable names in to the plotCellVsReference testthat code.
Let me know which you think is better and I'll do it.

**Comment by LTLA** [comment]
Yes, that's much nicer. Might as well name all of them, doesn't cost anything and it'll save time for someone reading it down the road.

**Comment by dtm2451** [comment]
Names are added.  I think that makes this ready to merge?

**Pull request merged**
