### PR TITLE
require common genes to be subset of ref

### LINKED ISSUE #77: Error in intI(i, n = x@Dim[1], dn[[1]], give.dn = FALSE) :  invalid character indexing
Happens on this line in `.build_trained_index`:

```R
sr.out <- .scaled_colranks_safe(current[common, , drop = FALSE])
```

In my case, this occurs because `common` is not a subset of `row.names(current)`. This occurs because I passed `genes` in as the result of `scran::getTopMarkers` and then the `ref` SCE gets subset to include genes in common with the `test` SCE.

PR on way.

### PR DESCRIPTION
**Pull request by alexvpickering**
fixes #77

### CODE REVIEW

**Comment by LTLA** [comment]
Almost. You'll also have to run through `extra` to make sure they're intersected for all the individual character vectors, `classifySingleR`'s fine-tuning assumes all genes are available in the test data.

If you are confident enough, see if you can add a unit test in `test-train.R` for this situation.

**Comment by LTLA** [comment]
Also, do me a favor and create this PR from the `postrelease` branch. Then I can immediately propagate the change into BioC-release, which would be helpful for everyone involved.

**Comment by alexvpickering** [comment]
Not sure if I need to go back to recommit changes to `postrelease`? If so, let me know. Thanks for the great packages!

**Comment by LTLA** [comment]
Yes, I was hoping to have you recommit your changes to `postrelease` prior to the PR. Then I can just do a merge into both `master` and `RELEASE_3_10`. The problem with #79 is that the merge from `master` into `RELEASE_3_10` will cause some merge conflicts as well as adding some updates from the BioC-devel version that shouldn't yet exist in the BioC-release version.

Admittedly this isn't documented anywhere but you're the first person outside of the **SingleR** team to make a PR so I was just going to wing it.

**Comment by LTLA** [comment]
I'm going to close this one, but I look forward to another PR based off `postrelease`. Just to make things absolutely clear - make sure you `git checkout postrelease` in your forked repo, and then repeat the commits that you've done here.  If you've done it right, the PR should subsequently be directed to `postrelease` and just contain two commits. If not... we end up with the situation in #79.

**Pull request closed without merging**
