### PR TITLE
Made plotScoreDistribution function for new pruning method

### PR DESCRIPTION
**Pull request by dtm2451**
Function changes:

- removed the `plotScoresSingleCell` version entirely
- folded `plotScoresSingleLabel` into `plotScoresMultiLabels`
- Updated original `plotScoresMultiLabels` to `plotScoreDistribution`

plotScoreDistribution handles plotting...:

- raw scores
- delta between max and median scores for each cell
- delta between first and second best tuning-scores for each cell

... for each label.

Updated tests, docs, and namespace for these changes

Updated the main vignette for the new tuning method and visualizations

### CODE REVIEW

**Comment by dtm2451** [comment]
Note: I know we talked about the raw scores and delta functions being separate, but the code was functionally so similar that I rolled it all together.  Switching between scores representation is handled with the `show` parameter.

Planned future steps:

1.  I'd like to add optional display of an nmads cutoff as a horizontal bars (only when `show=delta.med`).  I've written code for this, but it isn't matching up with labels' actual prune status.  I'll add if I get that working.
2.  Remove `plotCellVsReference` as well.

**Comment by LTLA** [comment]
> I know we talked about the raw scores and delta functions being separate, but the code was functionally so similar that I rolled it all together.

Yes, that's fine, that's what I thought as well. You might want to expose all options in the function call, e.g., `show=c("scores", "delta.med")` or something like that.

**Comment by dtm2451** [comment]
I've added it into the documentation.

**Comment by LTLA** [comment]
I meant actually adding it to the function call, _a la_:

```r
plotScoreDistribution <- function(results, show = c("scores", "delta.med"), 
    labels = colnames(results$scores), size = 0.5, ncol = 5,
    dots.on.top = TRUE, colors = c("#F0E442", "#E69F00", "gray60")) {

# ... sometime later...
    show <- match.arg(show)
```

This way, it documents itself. Or at least it's a lot more explicit about what the other option is.

**Comment by dtm2451** [comment]
👍 Added to function call too.

**Pull request merged**
