### PR TITLE
Add additional reference datasets.

### PR DESCRIPTION
**Pull request by j-andrews7**
Adds 3 new immune reference datasets:
 - [DMAP (Novershtern 2011; GSE24759)](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE24759)
 - [DICE](https://dice-database.org)
 - [GSE107011 (Monaco et al, 2019)](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE107011)

I based everything off of @friedue's previous work, so it should be consistent.

### CODE REVIEW

**Comment by LTLA** [comment]
Looking at the vignette again. Not sure we need separate subsections for each dataset. It may be more readable to shovel these details into the help files for the relevant functions (if they're not there already), and leave readers of the vignette with an concise understanding of the available datasets. Most of the text is highly redundant with the table, or just irrelevant to the user.

**Comment by j-andrews7** [comment]
My original thought was to do exactly that - most of the help files for the functions have all this info and it kind of uglies up the vignette. I am fine with removing that and making sure the help functions are sufficient in my next PR if everyone agrees. @friedue, thoughts?

**Comment by friedue** [comment]
I agree that currently there's a lot of overlap between the help and the vignette, but I personally prefer reading vignettes to pulling out the help of individual functions. I also like having the option of easily extending the info in the vignette, e.g. by showing what happens when you assign the exact same data set with the different data sets. I'm also a big proponent of redundancy when it comes to documentation, but if it hurts everybody else's sentiments, I'm fine keeping it out of there and I'll just tend to it when I feel like it in my personal repo for now.

**Comment by LTLA** [comment]
Another option is to print the list of labels into the markdown output with `results="asis"`. Then we wouldn't have to maintain the lists manually, and people could still read them easily. But we should really get rid of separate section headers for each dataset and the extraneous quotes.

**Comment by friedue** [comment]
I'm sure there's a fancy `kable` command that may do the job beautifully

**Comment by j-andrews7** [comment]
Okay, I will change in that manner then. @friedue, some of that (i.e. using multiple reference datasets) will be in my vignette for the paper.

**Pull request merged**
