### PR TITLE
Allow users to control plotScoreHeatmap colors

### PR DESCRIPTION
**Pull request by dtm2451**
Add if{} to allow color control when `normalize == TRUE`

### CODE REVIEW

**Comment by dtm2451** [comment]
Added `color` as an explicit input

**Comment by LTLA** [comment]
Well, you still have to set `args$color <- color` if `color` is not `NULL`.

**Comment by LTLA** [comment]
I would recommend that your current lines 170-172 collapse back to:

```r
args$color <- viridis::viridis(100)
```

And then add somewhere in the vicinity of line 179:

```r
if (!is.null(color)) {
    args$color <- color
}
```

This will overwrite any color added by `normalize=TRUE`, but it will also behave sensibly if `color=NULL` in that the argument is removed entirely from `args` (thus not affecting the default `color=` setting that might be in `pheatmap`).

**Comment by dtm2451** [comment]
Before seeing this, it’s what I had settled on too!  Was just gonna test a bit before committing.

(Sorry I’ve been absent recently.  My paper + pushing from my newer co-mentor to get work done on totally different project has left unfortunately little time for me to focus on package dev recently.)
_______________________________
Daniel Bunis
PhD Candidate, Burt & Sirota Labs
Biomedical Sciences Program
University of California, San Francisco
He/Him/His
daniel.bunis@ucsf.edu<mailto:daniel.bunis@ucsf.edu>
856-905-0499

On Feb 3, 2020, at 9:01 PM, Aaron Lun <notifications@github.com<mailto:notifications@github.com>> wrote:


I would recommend that your current lines 170-172 collapse back to:

args$color <- viridis::viridis(100)

And then add somewhere in the vicinity of line 179:

if (!is.null(color)) {
    args$color <- color
}

This will overwrite any color added by normalize=TRUE, but it will also behave sensibly if color=NULL in that the argument is removed entirely from args (thus not affecting the default color= setting that might be in pheatmap).

**Comment by dtm2451** [comment]
In testing, I've found providing users access to colors may get buggy / confusing when `normalize = FALSE`.  Because of line 175 (`args$breaks <- seq(-abs.max, abs.max, length.out = 101)`), for the example given in #91, instead of using the users requested ramp with 1000 cuts, only a portion is used.

**Comment by LTLA** [comment]
Guess we can check whether colors is specified, and if so, the `length.out` to `length(colors) + 1`. Otherwise set it to 101.

**Comment by dtm2451** [comment]
Seems to work =)

**Comment by LTLA** [comment]
Isn't it `length(color)+1`? See `breaks` in `?pheatmap`.

**Comment by dtm2451** [comment]
Yes, yes it is.

**Comment by LTLA** [comment]
Closes #91.

**Pull request merged**
