### PR TITLE
Added show.colnames input to plotScoreHeatmap

### PR DESCRIPTION
**Pull request by dtm2451**
Added an input for providing control of whether column names should be shown, per discussion in #57.

### CODE REVIEW

**Comment by LTLA** [comment]
Probably should use `_` to match up with the `pheatmap` docs, just to keep things simple. I know it's not consistent with our other arguments but that's okay; you can even do:

```
#' @param annotation_cols,show_colnames Other arguments to pass to \code{\link{pheatmap}}.
```

And so we can wash our hands of having to describe them at all.

**Comment by dtm2451** [comment]
wonderful idea!

**Comment by LTLA** [comment]
That note about `annotation_cols` is better placed in the Details.

**Comment by dtm2451** [comment]
Ultimately decided that I like explaining show_columns and annotation_col somewhat.  They really are quite useful, so I like pointing the use out.

**Pull request merged**
